In [23]:
import pandas as pd
import streamlit as st
import plotly.express as px
import numpy as np

data=pd.read_csv('vehicles_us.csv')


data.head()

price  model_year           model  condition  cylinders fuel  odometer  \
0   9400      2011.0          bmw x5       good        6.0  gas  145000.0   
1  25500         NaN      ford f-150       good        6.0  gas   88705.0   
2   5500      2013.0  hyundai sonata   like new        4.0  gas  110000.0   
3   1500      2003.0      ford f-150       fair        8.0  gas       NaN   
4  14900      2017.0    chrysler 200  excellent        4.0  gas   80903.0   

  transmission    type paint_color  is_4wd date_posted  days_listed  
0    automatic     SUV         NaN     1.0  2018-06-23           19  
1    automatic  pickup       white     1.0  2018-10-19           50  
2    automatic   sedan         red     NaN  2019-02-07           79  
3    automatic  pickup         NaN     NaN  2019-03-22            9  
4    automatic   sedan       black     NaN  2019-04-02           28

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   price         51525 non-null  int64  
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  object 
 3   condition     51525 non-null  object 
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  object 
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  object 
 8   type          51525 non-null  object 
 9   paint_color   42258 non-null  object 
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  object 
 12  days_listed   51525 non-null  int64  
dtypes: float64(4), int64(2), object(7)
memory usage: 5.1+ MB


In [25]:
data.describe(include='all')

price    model_year       model  condition     cylinders  \
count    51525.000000  47906.000000       51525      51525  46265.000000   
unique            NaN           NaN         100          6           NaN   
top               NaN           NaN  ford f-150  excellent           NaN   
freq              NaN           NaN        2796      24773           NaN   
mean     12132.464920   2009.750470         NaN        NaN      6.125235   
std      10040.803015      6.282065         NaN        NaN      1.660360   
min          1.000000   1908.000000         NaN        NaN      3.000000   
25%       5000.000000   2006.000000         NaN        NaN      4.000000   
50%       9000.000000   2011.000000         NaN        NaN      6.000000   
75%      16839.000000   2014.000000         NaN        NaN      8.000000   
max     375000.000000   2019.000000         NaN        NaN     12.000000   

         fuel       odometer transmission   type paint_color   is_4wd  \
count   51525   43633.000000        51525  51525       42258  25572.0   
unique      5            NaN            3     13          12      NaN   
top       gas            NaN    automatic    SUV       white      NaN   
freq    47288            NaN        46902  12405       10029      NaN   
mean      NaN  115553.461738          NaN    NaN         NaN      1.0   
std       NaN   65094.611341          NaN    NaN         NaN      0.0   
min       NaN       0.000000          NaN    NaN         NaN      1.0   
25%       NaN   70000.000000          NaN    NaN         NaN      1.0   
50%       NaN  113000.000000          NaN    NaN         NaN      1.0   
75%       NaN  155000.000000          NaN    NaN         NaN      1.0   
max       NaN  990000.000000          NaN    NaN         NaN      1.0   

       date_posted  days_listed  
count        51525  51525.00000  
unique         354          NaN  
top     2019-03-17          NaN  
freq           186          NaN  
mean           NaN     39.55476  
std            NaN     28.20427  
min            NaN      0.00000  
25%            NaN     19.00000  
50%            NaN     33.00000  
75%            NaN     53.00000  
max            NaN    271.00000

In [26]:
data.columns


Index(['price', 'model_year', 'model', 'condition', 'cylinders', 'fuel',
       'odometer', 'transmission', 'type', 'paint_color', 'is_4wd',
       'date_posted', 'days_listed'],
      dtype='object')

In [27]:
print(data.duplicated().sum())

0


In [28]:
data.isna().sum()

price               0
model_year       3619
model               0
condition           0
cylinders        5260
fuel                0
odometer         7892
transmission        0
type                0
paint_color      9267
is_4wd          25953
date_posted         0
days_listed         0
dtype: int64

In [29]:
print(data["condition"].sort_values().unique())

['excellent' 'fair' 'good' 'like new' 'new' 'salvage']


In [30]:
print(data["transmission"].sort_values().unique())

['automatic' 'manual' 'other']


In [31]:
print(data["paint_color"].sort_values().unique())

['black' 'blue' 'brown' 'custom' 'green' 'grey' 'orange' 'purple' 'red'
 'silver' 'white' 'yellow' nan]


In [32]:
data["paint_color"].isna().sum()

9267

In [33]:
data["paint_color"] = data["paint_color"].fillna('other')

In [34]:
data['is_4wd'].unique()

array([ 1., nan])

In [35]:
# Assuming that '1' is for Yes and Nan - 'No', replacing values and filling nulls with 'No'
data['is_4wd'] = data['is_4wd'].replace(1, 'Yes')

In [36]:
data['is_4wd'] = data['is_4wd'].fillna(value='No')

In [37]:
data['is_4wd'].unique()

array(['Yes', 'No'], dtype=object)

In [38]:
data["model_year"].unique()

array([2011.,   nan, 2013., 2003., 2017., 2014., 2015., 2012., 2008.,
       2018., 2009., 2010., 2007., 2004., 2005., 2001., 2006., 1966.,
       1994., 2019., 2000., 2016., 1993., 1999., 1997., 2002., 1981.,
       1995., 1996., 1975., 1998., 1985., 1977., 1987., 1974., 1990.,
       1992., 1991., 1972., 1967., 1988., 1969., 1989., 1978., 1965.,
       1979., 1968., 1986., 1980., 1964., 1963., 1984., 1982., 1973.,
       1970., 1955., 1971., 1976., 1983., 1954., 1962., 1948., 1960.,
       1908., 1961., 1936., 1949., 1958., 1929.])

In [39]:
#  Filling in the NaN values in model_year with median using group by model and model_year
data["model_year"] = pd.to_numeric(data["model_year"], errors="coerce")
data["model_year"] = data["model_year"].fillna(
    data.groupby("model")["model_year"].transform("median")
)

In [40]:
data["model_year"].unique()

array([2011. , 2013. , 2003. , 2017. , 2014. , 2015. , 2012. , 2008. ,
       2018. , 2009. , 2010. , 2007. , 2004. , 2005. , 2001. , 2006. ,
       1966. , 1994. , 2019. , 2000. , 2016. , 1993. , 1999. , 2006.5,
       1997. , 2002. , 1981. , 1995. , 1996. , 1975. , 1998. , 1985. ,
       1977. , 1987. , 1974. , 1990. , 1992. , 1991. , 1972. , 1967. ,
       1988. , 1969. , 1989. , 1978. , 1965. , 1979. , 1968. , 1986. ,
       1980. , 1964. , 1963. , 1984. , 1982. , 2010.5, 1973. , 1970. ,
       1955. , 1971. , 1976. , 1983. , 1954. , 1962. , 1948. , 1960. ,
       1908. , 1961. , 1936. , 1949. , 1958. , 1929. ])

In [41]:
data['model_year'].isna().sum()

0

In [42]:
data['cylinders'].unique()


array([ 6.,  4.,  8., nan,  5., 10.,  3., 12.])

In [43]:
data['cylinders'].isna().sum()

5260

In [44]:
data["cylinders"] = (
    data["cylinders"]
    .fillna(data.groupby(["model", "model_year"])["cylinders"].transform("mean"))
    .round()
)

In [45]:
# CHECK Filling in the NaN values in cylinders with mean using group by model and model_year
data["cylinders"] = pd.to_numeric(data["cylinders"], errors="coerce")
data["cylinders"] = data["cylinders"].fillna(
    data.groupby(["model", "model_year"])["cylinders"].transform('mean'))
data["cylinders"].unique()

array([ 6.,  4.,  8.,  5.,  7., 10., nan,  3.,  9., 12.])

In [46]:
data["cylinders"].isna().sum()

26

In [47]:
data = data.dropna(subset=['cylinders'])

In [48]:
data["cylinders"].isna().sum()

0

In [49]:
data['cylinders'].unique()

array([ 6.,  4.,  8.,  5.,  7., 10.,  3.,  9., 12.])

In [50]:
data['odometer'].isna().sum()

7885

In [51]:
#  Filling in the NaN values in odometer with median using group by model, model_year, type and condition
data["odometer"] = pd.to_numeric(data["odometer"], errors="coerce")
data["odometer"] = data["odometer"].fillna(
    data.groupby(["model", "model_year", "type", "condition"])["odometer"].transform(
        "median"
    )
)


In [52]:
data["odometer"].isna().sum()

603

In [53]:
 pd.options.mode.chained_assignment = None  
data["odometer"] = data["odometer"].fillna(
    data.groupby("model_year")["odometer"].transform(
        "mean"
    )
)

In [54]:
data[data['odometer'].isna()]

price  model_year       model condition  cylinders fuel  odometer  \
45694  18000      1929.0  ford f-150      good        8.0  gas       NaN   

      transmission   type paint_color is_4wd date_posted  days_listed  
45694       manual  other      silver     No  2018-11-18           59

In [55]:
data = data.drop(index=45694)

In [56]:
data["odometer"].isna().sum()

0

In [57]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51498 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   price         51498 non-null  int64  
 1   model_year    51498 non-null  float64
 2   model         51498 non-null  object 
 3   condition     51498 non-null  object 
 4   cylinders     51498 non-null  float64
 5   fuel          51498 non-null  object 
 6   odometer      51498 non-null  float64
 7   transmission  51498 non-null  object 
 8   type          51498 non-null  object 
 9   paint_color   51498 non-null  object 
 10  is_4wd        51498 non-null  object 
 11  date_posted   51498 non-null  object 
 12  days_listed   51498 non-null  int64  
dtypes: float64(3), int64(2), object(8)
memory usage: 5.5+ MB


In [58]:
data[data['price'] == 1].count()

price           798
model_year      798
model           798
condition       798
cylinders       798
fuel            798
odometer        798
transmission    798
type            798
paint_color     798
is_4wd          798
date_posted     798
days_listed     798
dtype: int64

In [59]:
data = data.drop(data[data['price'] == 1].index, axis=0, errors="raise")

In [60]:
data[data["price"] == 1].count()

price           0
model_year      0
model           0
condition       0
cylinders       0
fuel            0
odometer        0
transmission    0
type            0
paint_color     0
is_4wd          0
date_posted     0
days_listed     0
dtype: int64

In [61]:
data.describe(include="all")

price    model_year       model  condition     cylinders  \
count    50700.000000  50700.000000       50700      50700  50700.000000   
unique            NaN           NaN         100          6           NaN   
top               NaN           NaN  ford f-150  excellent           NaN   
freq              NaN           NaN        2733      24021           NaN   
mean     12323.447101   2009.719359         NaN        NaN      6.099862   
std       9996.468881      6.040884         NaN        NaN      1.633054   
min          3.000000   1908.000000         NaN        NaN      3.000000   
25%       5299.000000   2007.000000         NaN        NaN      4.000000   
50%       9495.000000   2011.000000         NaN        NaN      6.000000   
75%      16925.000000   2014.000000         NaN        NaN      8.000000   
max     375000.000000   2019.000000         NaN        NaN     12.000000   

         fuel       odometer transmission   type paint_color is_4wd  \
count   50700   50700.000000        50700  50700       50700  50700   
unique      5            NaN            3     13          13      2   
top       gas            NaN    automatic    SUV       white     No   
freq    46474            NaN        46406  12151        9877  25803   
mean      NaN  116666.694580          NaN    NaN         NaN    NaN   
std       NaN   62877.227432          NaN    NaN         NaN    NaN   
min       NaN       0.000000          NaN    NaN         NaN    NaN   
25%       NaN   73742.750000          NaN    NaN         NaN    NaN   
50%       NaN  115000.000000          NaN    NaN         NaN    NaN   
75%       NaN  154197.750000          NaN    NaN         NaN    NaN   
max       NaN  990000.000000          NaN    NaN         NaN    NaN   

       date_posted   days_listed  
count        50700  50700.000000  
unique         354           NaN  
top     2019-03-17           NaN  
freq           185           NaN  
mean           NaN     39.562682  
std            NaN     28.204562  
min            NaN      0.000000  
25%            NaN     19.000000  
50%            NaN     33.000000  
75%            NaN     53.000000  
max            NaN    271.000000

In [62]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50700 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   price         50700 non-null  int64  
 1   model_year    50700 non-null  float64
 2   model         50700 non-null  object 
 3   condition     50700 non-null  object 
 4   cylinders     50700 non-null  float64
 5   fuel          50700 non-null  object 
 6   odometer      50700 non-null  float64
 7   transmission  50700 non-null  object 
 8   type          50700 non-null  object 
 9   paint_color   50700 non-null  object 
 10  is_4wd        50700 non-null  object 
 11  date_posted   50700 non-null  object 
 12  days_listed   50700 non-null  int64  
dtypes: float64(3), int64(2), object(8)
memory usage: 5.4+ MB


In [63]:
data['transmission'].unique()

array(['automatic', 'manual', 'other'], dtype=object)

In [97]:
st.title(":red[Choose your car!]")
st.header(
    "Use this app to investigate different parameters of cars on the US market",
)


import urllib.request
from PIL import Image

urllib.request.urlretrieve(
    "https://images.bauerhosting.com/legacy/empire-tmdb/films/920/images/a1MlbLBk5Sy6YvMbSuKfwGlDVlb.jpg?ar=16%3A9&fit=crop&crop=top&auto=format&w=1440&q=80",
    "gfg.png",
)

img = Image.open("gfg.png")

st.image(img)

st.subheader(":red[Choose your parameters:]")


price_range = st.slider("Price range:", value=(3, 375000))
st.markdown("Recommendation: lower the upper value to filter out outliers")

actual_range = list(range(price_range[0], price_range[1] + 1))

excellent = st.checkbox("Only excellent condition")


trans = st.selectbox("Choose transmission", ("all", "automatic", "manual"))

if trans == "all":
    if excellent:
        filtered_data = data[data.price.isin(actual_range)]
        filtered_data = filtered_data[filtered_data["condition"] == "excellent"]
    else:
        filtered_data = data[data.price.isin(actual_range)]
else:
    if excellent:
        filtered_data = data[data.price.isin(actual_range)]
        filtered_data = filtered_data[
            (filtered_data["condition"] == "excellent")
            & (filtered_data["transmission"] == trans)
        ]
    else:
        filtered_data = data[
            (data.price.isin(actual_range)) & (data["transmission"] == trans)
        ]


st.write("Here are your options with a split by price and model year")



In [98]:
fig = px.scatter(
    filtered_data, title="Model year's influence on price", x="price", y="model_year"
)
st.plotly_chart(fig)

fig2 = px.scatter(
    filtered_data, title="Prices acccording to condition", x="price", y="condition"
)
st.plotly_chart(fig2)

# Histogram showing the average price by color
fig3 = px.histogram(
    filtered_data,
    title="Average price by color",
    x="paint_color",
    y="price",
    histfunc="avg",
)
st.plotly_chart(fig3)

fig4 = px.histogram(
    filtered_data,
    title="Distribution of distance travelled by these cars",
    x="odometer",
)
st.plotly_chart(fig4)



DeltaGenerator()

In [87]:
counts = data["is_4wd"].value_counts().sort_index().reset_index()
counts.columns = ['is_4wd', 'count']
print(counts)

  is_4wd  count
0     No  25803
1    Yes  24897


In [90]:
fig5 = px.bar(
    counts,
    y='count',
    title="Distribution of distance travelled by these cars",
    x="is_4wd",
    color="is_4wd",
)

In [91]:
fig5.show()

In [105]:
st.write("Here is the list of recommended cars")
st.dataframe(filtered_data.sample(40))

DeltaGenerator()

#Histogram showing the average price by model
fig2 = px.histogram(filtered_data, title="Average price by model", x="model", y="price",histfunc="avg")
st.plotly_chart(fig2)


#scatterplot  with a split by price and condition

fig = px.scatter(filtered_data, title="Split of cars by price and condition", x="price", y="condition")           
st.plotly_chart(fig)


#creating slider for the price range and checkbox for the cars that have less then 10 years since production 
st.caption('Choose your parameters here')
price_range = st.slider(
     "What is your price range?",
     value=(1, 375000))

actual_range=list(range(price_range[0],price_range[1]+1))

not_old_cars = st.checkbox('Only cars less then 10 years old')

if not_old_cars:
    filtered_data=df[df.price.isin(actual_range)]
    df.model_year = df.model_year.astype(str)
    filtered_data=filtered_data[df.model_year>='2010']
else:
    filtered_data=df[df.price.isin(actual_range)]